# Generated by Django 4.1.6 on 2023-02-09 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['name'], 'verbose_name': 'Mis Departamento', 'verbose_name_plural': 'Areas de la empresa'},
        ),
    ]
